---
- name: Deploy Prometheus Metrics Microservice
  hosts: localhost
  connection: local
  become: no
  
  tasks:
    - name: Check if Python is installed
      command: python3 --version
      register: python_check
      changed_when: false
      
    - name: Create virtual environment
      become: no
      shell: |
        python3 -m venv venv
        source venv/bin/activate && pip install prometheus-client
      args:
        executable: /bin/bash
        
    - name: Stop any running microservice
      shell: |
        pkill -f "python3 app.py" || true
        sleep 2
      args:
        warn: no
        
    - name: Start microservice using virtual environment
      shell: |
        cd /workspaces/microservice-project
        source venv/bin/activate
        nohup python app.py > microservice.log 2>&1 &
        echo "Microservice started with PID: $!"
      args:
        executable: /bin/bash
      async: 5
      poll: 0
      register: service_start
      
    - name: Wait for service to start
      wait_for:
        port: 8080
        timeout: 10
        
    - name: Display service status
      debug:
        msg: |
          Microservice deployed successfully!
          Metrics available at: http://localhost:8080/metrics
          Log file: microservice.log
          Using Python virtual environment
