---
- name: Deploy Prometheus Metrics Microservice
  hosts: localhost
  connection: local
  become: no
  
  tasks:
    - name: Check if Python is installed
      command: python3 --version
      register: python_check
      changed_when: false
      
    - name: Install prometheus-client if needed
      pip:
        name: prometheus-client
        state: present
      when: python_check.rc == 0
      
    - name: Stop any running microservice
      shell: |
        pkill -f "python3 app.py" || true
        sleep 2
      args:
        warn: no  # Игнорируем ошибку если процесс не найден
        
    - name: Start microservice in background
      shell: |
        cd /workspaces/microservice-project
        nohup python3 app.py > microservice.log 2>&1 &
        echo "Microservice started with PID: $!"
      async: 5
      poll: 0
      register: service_start
      
    - name: Wait for service to start
      wait_for:
        port: 8080
        timeout: 10
        
    - name: Display service status
      debug:
        msg: |
          Microservice deployed successfully!
          Metrics available at: http://localhost:8080/metrics
          Log file: microservice.log
